- name: Update packages
  apt: update_cache=yes

- name: Install ansible apt dependecies
  apt: name={{ item }} state=installed
  with_items:
    - python-apt
    - aptitude

- name: Install common packages
  apt: name={{ item }} state=installed
  with_items:
    - screen
    - tmux
    - zsh
    - xclip
    - exuberant-ctags
    - build-essential
    - libssl-dev
    - git
    - vim
    - htop
    - ack-grep
    - dnsutils
    - wget
    - ca-certificates
    - curl
    - libcurl4-openssl-dev
    - unzip
    - imagemagick
    - libmagickwand-dev
    - libreadline-dev
