- name: Add PostgreSQL-9.4 repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- name: Add PostgreSQL-9.4 key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Install PostgreSQL
  apt: name={{ item }} state=installed force=yes
  with_items:
    - postgresql-{{ pg.version }}
    - postgresql-contrib-{{ pg.version }}
    - postgresql-server-dev-{{ pg.version }}
  notify:
    - restart postgresql

- name: Install psycopg2, used by postgresql_* modules
  apt: name=python-psycopg2 state=installed

- name: Listen on all interfaces
  lineinfile: dest=/etc/postgresql/{{ pg.version }}/main/postgresql.conf
              regexp="listen_addresses = "
              line="listen_addresses = '*'"
              state=present
  notify:
    - restart postgresql

- name: Create hstore,intarray extensions in template1 database
  command: psql -d template1 -c "CREATE EXTENSION IF NOT EXISTS {{ item }}"
  with_items:
    - 'hstore'
    - 'intarray'
    - 'btree_gin'
  sudo: True
  sudo_user: postgres
